# Generated by Django 2.2.3 on 2019-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mail', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.IntegerField(default=0)),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('units_traded', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume_1day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume_7day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fluctate_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fluctate_rate_24h', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
